/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.sesion;

import ec.edu.ups.controladores.Persona_Controlador;
import ec.edu.ups.controladores.Usuario_Controlador;
import ec.edu.ups.modelo.Persona;
import ec.edu.ups.modelo.Usuario;
import ec.edu.ups.vista.MenuPrincipal;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
/**
 *
 * @author Byron
 */
public class Registro1 extends javax.swing.JInternalFrame {
  private Usuario_Controlador usuario_Controlador;
    private Persona_Controlador persona_Controlador;
    public static String x;
    private SimpleDateFormat formato;
    public Inicio_Sesion inicio_Sesion;
            
    String url = "jdbc:postgresql://localhost:5432/Proyecto_Interciclo";
    String user = "postgres";
    String password = "QLJPikrq7833";
    /**
     * Creates new form Registro1
     */
    public Registro1(String url, String user, String password) {
        initComponents();
         this.persona_Controlador = new Persona_Controlador(url, user, password);
        this.usuario_Controlador = new Usuario_Controlador(url, user, password);
        formato = new SimpleDateFormat("yyyy-MM-dd");
        x = "x";
        
        int a = Inicio_Sesion.panel.getWidth() - this.getWidth();
        int b = Inicio_Sesion.panel.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        txtcodigo1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtcedula1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtusuario1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfecha1 = new javax.swing.JTextField();
        txtcontraseña1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtapellido1 = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txttarjeta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        jLabel12.setText("Codigo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtcodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigo1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 38, -1));

        jLabel13.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        jLabel13.setText("Nombre:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtnombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 99, -1));

        jLabel14.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        jLabel14.setText("Cédula:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(txtcedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, -1));

        jLabel15.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        jLabel15.setText("Usuario:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, -1));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        jLabel5.setText("Fecha Nacimineto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(txtfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, -1));
        getContentPane().add(txtcontraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 103, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        jLabel3.setText("Tarjeta Crédito:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        jLabel16.setText("Apellido:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        txtapellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellido1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 103, -1));

        btnCrear.setText("Crear Usuario");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        btnCancelar.setText("Volver");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 94, -1));

        txttarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(txttarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 100, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/fondoventabas.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigo1ActionPerformed

    private void txtnombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre1ActionPerformed

    private void txtusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario1ActionPerformed

    private void txtapellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellido1ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Usuario usuario2 = new Usuario();
        usuario2.setUsuario(txtusuario1.getText());
        usuario2.setPassword(txtcontraseña1.getText());
        usuario2.setCodigo(Integer.parseInt(txtcodigo1.getText()));
        usuario2.setTarjeta_credito(txttarjeta.getText());
        usuario_Controlador.create(usuario2);

        Persona persona2 = new Persona();
        try {

            persona2.setCodigo(Integer.parseInt(txtcodigo1.getText()));
            persona2.setCedula(txtcedula1.getText());
            persona2.setNombre(txtnombre1.getText());
            persona2.setApellido(txtapellido1.getText());
            persona2.setFechaNac(formato.parse(txtfecha1.getText()));
            persona_Controlador.create(persona2);
        } catch (ParseException ex) {
            Logger.getLogger(Registro1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Registro1.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Usuaio Creado", "Crear Usuario", JOptionPane.OK_OPTION);

        txtapellido1.setText("");
        txtcedula1.setText("");
        txtcodigo1.setText("");
        txtcontraseña1.setText("");
        txtfecha1.setText("");
        txtnombre1.setText("");
        txtusuario1.setText("");
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        x=null;
        this.setVisible(false);
        this.dispose();
       
      
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txttarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtcedula1;
    private javax.swing.JTextField txtcodigo1;
    private javax.swing.JTextField txtcontraseña1;
    private javax.swing.JTextField txtfecha1;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txttarjeta;
    private javax.swing.JTextField txtusuario1;
    // End of variables declaration//GEN-END:variables
}
